// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgrAXlRlCrV1T_sDGztiVEmQpuL-R_vUI',
    appId: '1:885042257592:web:578953e09982c8a24b9e4d',
    messagingSenderId: '885042257592',
    projectId: 'hw2mad',
    authDomain: 'hw2mad.firebaseapp.com',
    storageBucket: 'hw2mad.firebasestorage.app',
    measurementId: 'G-ZB1MC9W8PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mxDhK-so0CE8quwwLXOcF4lKiNhgbeo',
    appId: '1:885042257592:android:8daae9746dd4276a4b9e4d',
    messagingSenderId: '885042257592',
    projectId: 'hw2mad',
    storageBucket: 'hw2mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrCCX2EMpVYG-jhRrdTvz6NU-oJ2rLtI',
    appId: '1:885042257592:ios:941d0ae1f384a96e4b9e4d',
    messagingSenderId: '885042257592',
    projectId: 'hw2mad',
    storageBucket: 'hw2mad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrCCX2EMpVYG-jhRrdTvz6NU-oJ2rLtI',
    appId: '1:885042257592:ios:941d0ae1f384a96e4b9e4d',
    messagingSenderId: '885042257592',
    projectId: 'hw2mad',
    storageBucket: 'hw2mad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgrAXlRlCrV1T_sDGztiVEmQpuL-R_vUI',
    appId: '1:885042257592:web:00f580baf77289174b9e4d',
    messagingSenderId: '885042257592',
    projectId: 'hw2mad',
    authDomain: 'hw2mad.firebaseapp.com',
    storageBucket: 'hw2mad.firebasestorage.app',
    measurementId: 'G-5X8173T54M',
  );

}